Feature/flexible section
BMW-Importer/metafox-sites pull request #133
Opened 2024-04-26 16:11 UTC by JDRoy93

https://feature-flexible-section--metafox-sites--bmw-importer.hlx.page

2024-04-26 16:20 UTC, aadityabatra approved these changes

2024-04-26 16:22 UTC, Harish-DV approved these changes
Can you please try using grid instead of Flex box

2024-04-26 16:27 UTC, Harish-DV requested changes
Can you please check the use of Grid instead of Flex box ? 
I  think its easier to manage this way.

2024-05-02 10:29 UTC, Harish-DV approved these changes

2024-05-02 10:29 UTC, merged