flex section js and css added
BMW-Importer/metafox-sites pull request #149
Opened 2024-05-02 14:47 UTC by JDRoy93

https://feature-flex-section--metafox-sites--bmw-importer.hlx.page/test-pages/index-copy/page-with-deafultblocks

2024-05-03 11:04 UTC, Buuhuu commented on blocks/flexible-width-section/flexible-width-section.css
> +.section.center.grid-6 .button-container > .align-icon,
You can consolidate these listing of long selectors with `:where()`

```.section.center:where(.grid-6,.grid-8,.grid-10) .button-container > .align-icon```

2024-05-03 11:31 UTC, JDRoy93 commented on blocks/flexible-width-section/flexible-width-section.css
> +.section.center.grid-6 .button-container > .align-icon,
Updated

2024-05-04 05:59 UTC, Harish-DV requested changes
Comments from Adobe

why is identifier hidden? without a condition it will never show, no?
if you insist on having multiple properties on the section instead of a multi-select style field, better give them meaningful names like gridWidth and alignment instead of styles and classes. Only the styles key has a special purpose and becomes a css class. Everything else is just a data attribute. You can use the data attributes in css selectors as well so that is fine.
you do not need a custom decorateSections implementation. Section metadata becomes data attributes which are accessible in css selectors. If you want them to be class names you can use your own decorate function in addition to the one from aem.js (as in runs after decorateSections, reads data attributes and converts them to classes)
you must not remove decorateSections from decorateMain
if you add custom decorations to decorateMain make sure to add them to the editor-support.js script as well

2024-05-06 09:36 UTC, bharath-yathiraj approved these changes
approved

2024-05-06 13:43 UTC, Harish-DV approved these changes

2024-05-06 13:43 UTC, merged