Feature/metafox 1745 button bug
BMW-Importer/metafox-sites pull request #445
Opened 2024-06-28 13:33 UTC by Tsivani91

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--metafox-sites--bmw-importer.hlx.page/
- After: https://feature-metafox-1745-button-bug--metafox-sites--bmw-importer.hlx.page/
![image](https://github.com/BMW-Importer/metafox-sites/assets/170097734/17717a11-428f-4c2b-ae17-9c2afa71bb02)

2024-06-28 13:41 UTC, babita1998 approved these changes

2024-06-28 13:45 UTC, babita1998 requested changes
class name is not correct plea

2024-06-28 13:48 UTC, babita1998 approved these changes

2024-07-01 03:42 UTC, AmolYPatil approved these changes

2024-07-01 03:42 UTC, merged